# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('org_name', models.CharField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('logo', models.URLField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
            preserve_default=False,
        ),
    ]
