# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180711_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='driver_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
