# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogs',
            name='status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
