# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_devicelogs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='subscription_ends',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 12, 8, 3, 210000, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
