# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_device_subscription_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogs',
            name='ignition_status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='on', max_length=3),
            preserve_default=False,
        ),
    ]
