# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_devicelogs_ignition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogs',
            name='door_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicelogs',
            name='ac_status',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=3),
        ),
        migrations.AlterField(
            model_name='devicelogs',
            name='ignition_status',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=3),
        ),
    ]
